import { UserProfile } from './types';

export const sampleProfiles: Record<string, UserProfile> = {
  sarah: {
    name: 'Sarah (Bio-Hacker)',
    age: 42,
    gender: 'female',
    height: 165,
    weight: 54,
    sleepHours: 8.5,
    restingHeartRate: 48,
    systolicBP: 105,
    diastolicBP: 68,
    exerciseDaysPerWeek: 6,
    dietQuality: 9,
    smokingStatus: 'never',
    alcoholDrinksPerWeek: 0,
    stressLevel: 2,
    fastingGlucose: 78,
    totalCholesterol: 160,
    hdlCholesterol: 85,
    ldlCholesterol: 70,
    familyHistory: {
      heartDisease: false,
      diabetes: false,
      hypertension: false,
      cancer: false,
      mentalHealth: false,
    },
  },
  vikram: {
    name: 'Vikram (Tech Lead)',
    age: 38,
    gender: 'male',
    height: 178,
    weight: 92,
    sleepHours: 4.5,
    restingHeartRate: 88,
    systolicBP: 145,
    diastolicBP: 95,
    exerciseDaysPerWeek: 0,
    dietQuality: 3,
    smokingStatus: 'never',
    alcoholDrinksPerWeek: 8,
    stressLevel: 10,
    fastingGlucose: 110,
    totalCholesterol: 255,
    hdlCholesterol: 32,
    ldlCholesterol: 185,
    familyHistory: {
      heartDisease: true,
      diabetes: true,
      hypertension: true,
      cancer: false,
      mentalHealth: true,
    },
  },
  riya: {
    name: 'Riya (Academic)',
    age: 32,
    gender: 'female',
    height: 163,
    weight: 68,
    sleepHours: 5,
    restingHeartRate: 82,
    systolicBP: 128,
    diastolicBP: 84,
    exerciseDaysPerWeek: 1,
    dietQuality: 4,
    smokingStatus: 'never',
    alcoholDrinksPerWeek: 3,
    stressLevel: 8,
    fastingGlucose: 105,
    totalCholesterol: 220,
    hdlCholesterol: 42,
    ldlCholesterol: 140,
    familyHistory: {
      heartDisease: true,
      diabetes: true,
      hypertension: true,
      cancer: false,
      mentalHealth: false,
    },
  },
  arjun: {
    name: 'Arjun (Sales)',
    age: 45,
    gender: 'male',
    height: 175,
    weight: 88,
    sleepHours: 6,
    restingHeartRate: 78,
    systolicBP: 138,
    diastolicBP: 88,
    exerciseDaysPerWeek: 2,
    dietQuality: 5,
    smokingStatus: 'former',
    alcoholDrinksPerWeek: 5,
    stressLevel: 7,
    fastingGlucose: 118,
    totalCholesterol: 245,
    hdlCholesterol: 38,
    ldlCholesterol: 160,
    familyHistory: {
      heartDisease: true,
      diabetes: true,
      hypertension: false,
      cancer: false,
      mentalHealth: true,
    },
  },
  priya: {
    name: 'Priya (Athlete)',
    age: 28,
    gender: 'female',
    height: 168,
    weight: 58,
    sleepHours: 8,
    restingHeartRate: 58,
    systolicBP: 110,
    diastolicBP: 72,
    exerciseDaysPerWeek: 5,
    dietQuality: 8,
    smokingStatus: 'never',
    alcoholDrinksPerWeek: 1,
    stressLevel: 3,
    fastingGlucose: 85,
    totalCholesterol: 175,
    hdlCholesterol: 62,
    ldlCholesterol: 90,
    familyHistory: {
      heartDisease: false,
      diabetes: false,
      hypertension: false,
      cancer: false,
      mentalHealth: false,
    },
  },
};

export const getDefaultProfile = (): UserProfile => ({
  name: '',
  age: 30,
  gender: 'male',
  height: 170,
  weight: 70,
  sleepHours: 7,
  restingHeartRate: 72,
  systolicBP: 120,
  diastolicBP: 80,
  exerciseDaysPerWeek: 3,
  dietQuality: 5,
  smokingStatus: 'never',
  alcoholDrinksPerWeek: 2,
  stressLevel: 5,
  familyHistory: {
    heartDisease: false,
    diabetes: false,
    hypertension: false,
    cancer: false,
    mentalHealth: false,
  },
});
